[package]
name = "bluest_one"
version = "0.1.0"
edition = "2024"

[dependencies]
bluest = { version = "0.6.8", features = ["serde"] }
futures = "0.3.31"
tokio = { version = "1.45.1", features = ["full"] }
